language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t brianc/docker-react -f Dockerfile.dev .
    
script: 
  - docker run -e CI=true brianc/docker-react npm run test

